import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Nav from "./nav";
import Providers from "./providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  homeBanner1: React.ReactNode;
  homeBanner2: React.ReactNode;
};

export default function RootLayout({
  children,
  homeBanner1,
  homeBanner2,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={"p-4"}>
        <Providers>
          <Nav />
          {homeBanner1}
          {homeBanner2}
          {children}
        </Providers>
      </body>
    </html>
  );
}
